local m = require("src.model")
local funcs = require("src.funcs")
local st = m.singleTasks
local wt = m.weeklyTask
local yt = m.yearlyTask
local td = m.timedelta
local bd = m.birthdayTask
local wt5 = function(name)
	return wt(name, 5)
end
local et = m.eventTask
return {
	wt("shave"),
	wt("check emails"),
	wt("nix flake update"),
	wt5("clean"),
	wt5("cut nails"),
	wt5("clear tabs"),
	wt5("clean toothbrush"),
	wt5("laundry"),
	wt5("change towel"),
	{
		name = m.just("Humble Bundle"),
		conditions = { m.isDayOfWeek(2), m.isWeekOfMonth(1, m.timedelta(0, -17)) },
		-- -17 cause PST is 17 hours behind my time zone, its actually wednesday too
		duetime = m.dueTime(m.timedelta(30)),
		checkstart = function(date)
			return funcs.floorToDay(date) - m.timedelta(31) + m.timedelta(0, 3)
			-- 3 hours cause 3 am
		end,
		checkrepeats = m.justRepeats(2),
		finishdelta = m.just(m.timedelta(0)),
	},
	yt("Firmware Update (fwupd)"),
	yt("Wash Backpack"),
	-- m.multiWeekTask("exercise", { 0, 1, 3, 5, 6, 7 }),
	(function()
		local x = m.multiWeekTask("exercise", { 0, 1, 3, 5, 6 })
		x.duetime = m.dueTime(td(2))
		return x
	end)(),
	m.nthWeekTask("clean dakimura...", 6, 5),
	m.nthWeekTask("clean Pillow/Sheets", 3, 5),
	m.nthWeekTask("clean phone", 3, 5),
	m.nthWeekTask("clean blanket", 12, 5),
	m.nthWeekTask("clean laptop/computer", 30, 5),
	m.nthWeekTask("clean keyboard/mouse", 30, 5),
	m.nthWeekTask("top up bus card", 2),
	m.seasonalTask("trackmania", 2),
	bd("Phoenix Gosper", 2, 16),
	bd("Sam", 2, 27),
	bd("Liam", 3, 4),
	bd("Luka", 3, 4),
	bd("Bernaburger", 3, 9),
	bd("George", 3, 11),
	bd("Stefchan", 3, 21),
	bd("Kevin", 3, 22),
	bd("Akira", 5, 19),
	bd("Luke", 7, 19),
	bd("Emaan", 8, 10),
	bd("Holly", 8, 19),
	bd("Audrey", 8, 24),
	bd("Sean", 9, 10),
	bd("Chris", 9, 14),
	bd("Warnaburger", 10, 4),
	bd("Benji", 10, 8),
	bd("Taj", 10, 28),
	bd("Shane", 10, 31),
	bd("Char", 12, 17),
	bd("Dung", 12, 29),
	et("Bsides canberra", 24, 9, 2026),
	st({
		"Test works",
		"bin scripts instead of hypr nixos",
		"neovim config (vim pack) treesit (ctrl backspace)",
		"declarative flatpak/roblox",
		"lua library lsp lazydev",
		"millenium nix",
		"steam notifications wayland work",
		"humble bundle tasks",
		"Stitch pants",
		"cadetship",
		"git fetch to burrsgs",
		"vanguard stocks, jk government bonds",
		"move games to wishlist steam",
		"clean megumin pillow",
		"wakeup checklist",
		"anu cssa",
		"Integrate gaussian distribution e^-x^2",
		"Proportional derivative controller engn",
		"vpython nix",
		"Go through emails",
		"gum cli addage to todo",
		"Go through all todo in taskmanger",
		"bsides/csides canberra",
		"Ctrl Backspace nvim",
		"get logseq todo in this",
		"message tax file number and supperannuation",
		"pullup tower",
		"task manager flake (check notes)",
		"make/add scripts folder (check notes)",
		"Find a way to use old numbers/uni psw",
		"android text writing app instead of firefox",
		"turn task manager into flake(check notes)",
		"another rip in pants",
		"add attributes list to tasks(check notes)",
		"find the anthony edwards defense video olympics",
		"Change tetrio pfp",
		"change android wallpaper",
		"Donate clothes",
		"accumulate tasks (check notes)",
		"home manager (replace stow)",
		"debloat computer",
		"shellnix/devenvs",
		"gitignore vesktop and fonts",
		"wlrwhichkey and submaps for opening apps",
		"Package my pomodoro script",
		"abuse the welfare system",
		"change fonts for all default programs.",
		"pomodoro program(check notes)",
		"macros logseq",
		"bitwarden/shitwarden or proton",
		"remove json5",
		"neomutt",
		"logseq and hyprland clear notofications keybind",
		"do something about burrsgs",
		"weekly tasks check notes",
		"replace goonroll",
		"buy gloves",
		"burrsgs pull/push confirmation",
		"replace phone alarm",
		"package micromouse",
		"rustlings",
		"test1",
		"test1",
		"Music task idea(check notes)",
		"Package all anki addons. (cn)",
		"remove neovim text wrapper.",
		"raspberry pi alarm (cn)",
		"task luarc json",
		"firmwareupdate task",
		"packages anki addons (cn)",
		"package luarocks",
		"osu",
		"burrsgs (cn)",
		"seasonal trackmania task",
		"laundry task",
		"efficient morning routine",
		"fuck youtube",
		"clean phone (task maybe)",
		"gymtask",
		"hyprland lua",
		"sheets pillowcase task",
		"home manager (cn)",
		"nvim per project exrc",
		"yearly task wash bag",
		"Check all nix community repos",
		"Top up bus card task",
		"Sleep at school once",
		"submit to the nix user repos",
		"make programmatic slideshows (cn)",
		"check camera roll",
		"home manager nvimdiff",
		"impermanence.nix",
		"Remove 'enable unfree' from nix",
		"Hyprland which key",
		"Attempt offline only again",
		"Check community.nix",
		"shorthand",
		"latex ocr",
		"nvim local config (cn)",
		"clean fuckass dirty bin",
		"nvim macros but in the whole computer",
		"New phone",
		"make a fetch",
		"Buy some books",
		"Practice/learn git fully",
		"Get git signing",
		"clean fuckass shoe",
		"Switch to nyxt or qute, or luakit",
		"neomutt",
		"Cli soundboard",
		"latex multiperson (cn)",
		"Bitwarden",
		"Spotify/music keeb only",
		"Images Spotify",
		"Room decoration, choose budcget",
		"Buylist",
		"Album",
		"Cook",
		"Clean fuckass lunchbag",
		"Firefox file manager to yazi",
		"I hate centrelink",
		"Switch to yarara",
		"Package fonts",
		"Fix yazi relative motions",
		"Create fastfetch for meself",
		"qr code tool like ocr",
		"Bashmarks rust",
		"Switch from spotify (cn)",
		"find a way to find music",
		"replace logseq with nvim",
		"Vimtex",
		"leechblock minutes per hour",
		"Blender to 3dprint.",
		"List of things in holiday(cn)",
		"Air fried potatoes",
		"Check reddit saved",
		"birthday task taskmanger",
		"weekly find book/manga task (more also)",
		"clean bathroom ceiling mould",
		"Portfolio website",
	}),
}
