hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/hypr/extra/scripts/volup.sh"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/hypr/extra/scripts/voldown.sh"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("~/.config/hypr/extra/scripts/outputmute.sh"), { locked = true })
hl.bind("mouse:279", hl.dsp.exec_cmd("~/.config/hypr/extra/scripts/inputmute.sh"), { locked = true, repeating = true })
hl.bind("code:201", hl.dsp.exec_cmd("~/.config/hypr/extra/scripts/inputmute.sh"), { locked = true, repeating = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("ddcutil setvcp 10 + 10"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("ddcutil setvcp 10 - 10"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl --player=spotify next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl --player=spotify play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl --player=spotify play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl --player=spotify previous"), { locked = true })
